[project]
name = "data-science-project"
version = "0.1.0"
description = "A Data Science project"
authors = [
    {name = "Simran"}
]
readme = "README.md"
requires-python = "^3.13"
dependencies = [
    "numpy (>=2.3.4,<3.0.0)",
    "pandas (>=2.3.3,<3.0.0)",
    "scikit-learn (>=1.7.2,<2.0.0)",
    "polars (>=1.35.2,<2.0.0)",
    "duckdb (>=1.4.1,<2.0.0)",
    "altair (>=5.5.0,<6.0.0)",
    "streamlit (>=1.51.0,<2.0.0)",
    "pydantic (>=2.12.4,<3.0.0)",
    "fastapi (>=0.121.1,<0.122.0)",
    "uvicorn (>=0.38.0,<0.39.0)",
    "shap (>=0.49.1,<0.50.0)",
    "vega-datasets (>=0.9.0,<0.10.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]

[tool.ruff]
select = ["E", "F", "B", "I"]
ignore = []
fixable = ["ALL"]
unfixable = []

[tool.black]
line-length = 88
target-version = ["py313"]

[dependency-groups]
dev = [
    "pytest (>=9.0.0,<10.0.0)",
    "pytest-cov (>=7.0.0,<8.0.0)",
    "black (>=25.9.0,<26.0.0)",
    "ruff (>=0.14.4,<0.15.0)",
    "pre-commit (>=4.4.0,<5.0.0)"
]
